# TODO(rogchap): Change to be just release tags
on: push

env:
  wombat-version: 0.2.0-dev # TODO(rogchap) Read this directly from the tag

jobs:
  package:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Chechout
      uses: actions/checkout@v2
    - name: Install Wails
      run: go get -u github.com/wailsapp/wails/cmd/wails@v1.9.1
    - name: Package for darwin
      if: matrix.platform == 'macos-latest'
      run: |
        mkdir -p ~/.wails
        cp wails.json ~/.wails/
        wails build -f -p -ldflags "-X wombat/internal/app.semver=${{ env.wombat-version }}"
    - name: Create darwin disk igage
      if: matrix.platform == 'macos-latest'
      run: |
        brew install create-dmg
        rm build/wombat
        create-dmg --volname "Wombat" --volicon "assets/darwin/dmg_icon.icns" --background "assets/darwin/dmg_bg.png" --window-size 512 360 --icon-size 100 --icon "Wombat.app" 100 185  --hide-extension "Wombat.app" --app-drop-link 388 185 "Wombat.dmg" "build"
    - name: Upload darwin artifact
      uses: actions/upload-artifact@v2
      with:
        name: Wombat_${{ env.wombat-version }}_Darwin_x86_64.dmg
        path: Wombat.dmg
